language: python

python:
 - "3.6"

 #command to install dependencies
install:
  - "pip install -r requirements.txt"

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE test_store_manager;' -U postgres

# command to run tests
script:
  - nosetests --with-coverage --cover-package=modules.app

after_success:
  - coveralls