language: python

python:
 - "3.6"

 #command to install dependencies
install:
  - "pip install -r requirements.txt"

services:
  - postgresql



addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
  - PGUSER=postgres
  - PGHOST=localhost


before_script:
  - psql -c 'CREATE DATABASE test_store_manager;' -U postgres

# command to run tests
script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls