language: python

python:
 - "3.6"

 #command to install dependencies
install:
  - "pip install -r requirements.txt"

services:
  - postgresql



test:
  adapter: postgresql
  database: test_store_manager

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

before_script:
  - psql -c 'CREATE DATABASE test_store_manager;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres




# command to run tests
script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls